[["/home/ec2-user/.local/lib/python3.9/site-packages/email_validator/__init__.py",[false,[["ValidatedEmail",true,2,["ValidatedEmail","/home/ec2-user/.local/lib/python3.9/site-packages/email_validator/exceptions_types.py",5]],["EmailNotValidError",true,2,["EmailNotValidError","/home/ec2-user/.local/lib/python3.9/site-packages/email_validator/exceptions_types.py",5]],["EmailSyntaxError",true,2,["EmailSyntaxError","/home/ec2-user/.local/lib/python3.9/site-packages/email_validator/exceptions_types.py",5]],["EmailUndeliverableError",true,2,["EmailUndeliverableError","/home/ec2-user/.local/lib/python3.9/site-packages/email_validator/exceptions_types.py",5]],["__all__",true,13,null],["caching_resolver",true,12,null],["ALLOW_SMTPUTF8",true,14,null],["ALLOW_QUOTED_LOCAL",true,14,null],["ALLOW_DOMAIN_LITERAL",true,14,null],["GLOBALLY_DELIVERABLE",true,14,null],["CHECK_DELIVERABILITY",true,14,null],["TEST_ENVIRONMENT",true,14,null],["DEFAULT_TIMEOUT",true,14,null],["SPECIAL_USE_DOMAIN_NAMES",true,14,null]]]]]